class Static {
  static const definition =
      "Pneumonia is an infection that inflames the air sacs in one or both lungs The air sacs may fill with fluid or pus (purulent material), causing cough with phlegm or pus, fever, chills, and difficulty breathing.A variety of organisms, including bacteria, viruses and fungi, can cause pneumonia.Pneumonia can range in seriousness from mild to life-threatening.It is most serious for infants and young children, people older than age 65, and people with health problems or weakened immune systems.";
  static const cause =
      "Many germs can cause pneumonia. The most common are bacteria and viruses in the air we breathe. Your body usually prevents these germs from infecting your lungs. But sometimes these germs can overpower your immune system, even if your health is generally good.Pneumonia is classified according to the types of germs that cause it and where you got the infection.Community-acquired pneumonia:Community-acquired pneumonia is the most common type of pneumonia. It occurs outside of hospitals or other health care facilities. It may be caused by:\n- Bacteria: The most common cause of bacterial pneumonia in the U.S. is Streptococcus pneumoniae.This type of pneumonia can occur on its own or after you've had a cold or the flu.It may affect one part (lobe) of the lung, a condition called lobar pneumonia.\n- Bacteria-like organisms: Mycoplasma pneumoniae also can cause pneumonia.It typically produces milder symptoms than do other types of pneumonia. Walking pneumonia is an informal name given to this type of pneumonia, which typically isn't severe enough to require bed rest.\n- Fungi: This type of pneumonia is most common in people with chronic health problems or weakened immune systems, and in people who have inhaled large doses of the organisms.The fungi that cause it can be found in soil or bird droppings and vary depending upon geographic location.\n- Viruses: including COVID-19, Some of the viruses that cause colds and the flu can cause pneumonia.Viruses are the most common cause of pneumonia in children younger than 5 years.Viral pneumonia is usually mild. But in some cases it can become very serious. Coronavirus 2019 (COVID-19) may cause pneumonia, which can become severe.";
  static const risk =
      "Pneumonia can affect anyone. But the two age groups at highest risk are:\n- Children who are 2 years old or younger.\n- People who are age 65 or older.\nOther risk factors include:]n- Being hospitalized: You're at greater risk of pneumonia if you're in a hospital intensive care unit, especially if you're on a machine that helps you breathe (a ventilator).\n- Chronic disease: You're more likely to get pneumonia if you have asthma, chronic obstructive pulmonary disease (COPD) or heart disease.\n- Smoking: Smoking damages your body's natural defenses against the bacteria and viruses that cause pneumonia.\n- Weakened or suppressed immune system: People who have HIV/AIDS, who've had an organ transplant, or who receive chemotherapy or long-term steroids are at risk.";
  static const type =
      "- Community-acquired pneumonia (CAP)\n- Hospital-acquired pneumonia (HAP)\n- Healthcare-associated pneumonia (HCAP)\n- Ventilator-associated pneumonia (VAP)";
  static const symptoms =
      "The signs and symptoms of pneumonia vary from mild to severe, depending on factors such as the type of germ causing the infection, and your age and overall health. Mild signs and symptoms often are similar to those of a cold or flu, but they last longer.Signs and symptoms of pneumonia may include:\n- Chest pain when you breathe or cough.\n- Confusion or changes in mental awareness (in adults age 65 and older).\n- Nausea and vomiting, especially in small children.\n- Cough, which may produce phlegm.\n- Fatigue.\n- Fever, sweating and shaking chills.\n- Lower than normal body temperature (in adults older than age 65 and people with weak immune systems).\n- Nausea, vomiting or diarrhea.\n- Shortness of breath.\nNewborns and infants may not show any sign of the infection. Or they may vomit, have a fever and cough, appear restless or tired and without energy, or have difficulty breathing and eating.";
  static const complications =
      "Even with treatment, some people with pneumonia, especially those in high-risk groups, may experience complications, including:\n- Bacteria in the bloodstream (bacteremia):Bacteria that enter the bloodstream from your lungs can spread the infection to other organs, potentially causing organ failure.\n- Difficulty breathing:If your pneumonia is severe or you have chronic underlying lung diseases, you may have trouble breathing in enough oxygen. You may need to be hospitalized and use a breathing machine (ventilator) while your lung heals.\n- Fluid accumulation around the lungs (pleural effusion):Pneumonia may cause fluid to build up in the thin space between layers of tissue that line the lungs and chest cavity (pleura). If the fluid becomes infected, you may need to have it drained through a chest tube or removed with surgery.\n- Lung abscess:\nAn abscess occurs if pus forms in a cavity in the lung. An abscess is usually treated with antibiotics. Sometimes, surgery or drainage with a long needle or tube placed into the abscess is needed to remove the pus.";
  static const prevention =
      "To help prevent the spread of pneumonia:\n- Get vaccinated:Vaccines are available to prevent some types of pneumonia and the flu. Talk with your doctor about getting these shots. The vaccination guidelines have changed over time so make sure to review your vaccination status with your doctor even if you recall previously receiving a pneumonia vaccine.\n- Make sure children get vaccinated:Doctors recommend a different pneumonia vaccine for children younger than age 2 and for children ages 2 to 5 years who are at particular risk of pneumococcal disease. Children who attend a group child care center should also get the vaccine. Doctors also recommend flu shots for children older than 6 months.\n- Practice good hygiene:To protect yourself against respiratory infections that sometimes lead to pneumonia, wash your hands regularly or use an alcohol-based hand sanitizer.\n- Don't smoke:Smoking damages your lungs' natural defenses against respiratory infections.\n- Keep your immune system strong:Get enough sleep, exercise regularly and eat a healthy diet.";
  static const suspiction =
      "If pneumonia is suspected, your doctor may recommend the following tests:\n- Blood tests:Blood tests are used to confirm an infection and to try to identify the type of organism causing the infection. However, precise identification isn't always possible.\n- Chest X-ray:This helps your doctor diagnose pneumonia and determine the extent and location of the infection. However, it can't tell your doctor what kind of germ is causing the pneumonia.\n- Pulse oximetry:This measures the oxygen level in your blood. Pneumonia can prevent your lungs from moving enough oxygen into your bloodstream.\n- Sputum test:A sample of fluid from your lungs (sputum) is taken after a deep cough and analyzed to help pinpoint the cause of the infection.Your doctor might order additional tests if you're older than age 65, are in the hospital, or have serious symptoms or health conditions. These may include:\n- CT scan:If your pneumonia isn't clearing as quickly as expected, your doctor may recommend a chest CT scan to obtain a more detailed image of your lungs.\n- Pleural fluid culture:A fluid sample is taken by putting a needle between your ribs from the pleural area and analyzed to help determine the type of infection.";
  static const treatment =
      "Treatment for pneumonia involves curing the infection and preventing complications. People who have community-acquired pneumonia usually can be treated at home with medication. Although most symptoms ease in a few days or weeks, the feeling of tiredness can persist for a month or more.Specific treatments depend on the type and severity of your pneumonia, your age and your overall health. The options include:\n- Antibiotics:These medicines are used to treat bacterial pneumonia. It may take time to identify the type of bacteria causing your pneumonia and to choose the best antibiotic to treat it. If your symptoms don't improve, your doctor may recommend a different antibiotic.\n- Cough medicine:This medicine may be used to calm your cough so that you can rest. Because coughing helps loosen and move fluid from your lungs, it's a good idea not to eliminate your cough completely.In addition, you should know that very few studies have looked at whether over-the-counter cough medicines lessen coughing caused by pneumonia. If you want to try a cough suppressant, use the lowest dose that helps you rest.\n- Fever reducers/pain relievers:You may take these as needed for fever and discomfort. These include drugs such as aspirin, ibuprofen (Advil, Motrin IB, others) and acetaminophen (Tylenol, others).";
  static const hospitalization =
      "You may need to be hospitalized if:\n- You are older than age 65.\n- You are confused about time, people or places.\n- Your kidney function has declined.\n- Your systolic blood pressure is below 90 millimeters of mercury (mm Hg) or your diastolic blood pressure is 60 mm Hg or below.\n- Your breathing is rapid (30 breaths or more a minute).\n- You need breathing assistance.\n- Your temperature is below normal.\n- Your heart rate is below 50 or above 100.You may be admitted to the intensive care unit if you need to be placed on a breathing machine (ventilator) or if your symptoms are severe.\nChildren may be hospitalized if:\n- They are younger than age 2 months.\n- They are lethargic or excessively sleepy.\n- They have trouble breathing.\n- They have low blood oxygen levels.\n- They appear dehydrated";
  static List<String> question = [
    'if your age more than or equal 65 then click yes.',
    'Do you have any chest morbidities?',
    'Do you smoke?',
    'Do you have history of asthma in your family?',
    'Did you catch the same condition before?',
    'Did you hospitalize as a case of pneumonia before?',
    'If yes, did that take more than two episodes a year?',
    "Did you receive any medication for pneumonia?",
    "Did you experience any long-term effects after recovering from pneumonia?",
    "Did you receive pneumonia vaccine before these symptoms? ",
    'Did you catch covid-19 virus? ',
    "Do you suffer from shortness of breaths?",
    ' Do you suffer from fever?',
    ' Do you suffer from Cough?',
    ' Do you suffer from chest pain?',
    'Do you feel your heartbeat? ',
    'Do you suffer from loss of appetite?',
    'Do you suffer from headache?',
    ' Do you suffer from mental confusion?',
    ' Do you suffer from fatigue?',
  ];

  static List<String> have = [
    "Do you suffer from shortness of breaths?",
    ' Do you suffer from fever?',
    ' Do you suffer from Cough?',
    ' Do you suffer from chest pain?',
    ' Do you suffer from mental confusion?',
  ];

  static List<String> propability = [
    'If yes, did that take more than two episodes a year?',
    "Did you experience any long-term effects after recovering from pneumonia?",
    "Did you receive pneumonia vaccine before these symptoms? ",
    'Did you catch covid-19 virus? ',
  ];
  static List<String> app = [];
  static const dontHave =
      "( You don't have Pneumonia) \nWe wanted to inform you about the results of your recent medical evaluation. After carefully reviewing your symptoms and diagnostic tests, we are pleased to inform you that you do not have pneumonia. While this is reassuring news, we understand that you may still be experiencing discomfort or symptoms that prompted you to seek medical attention. It's important to address these symptoms and identify their cause to ensure your health and well-being. \nWe recommend the following steps:\n - Follow-Up Appointment: Schedule a follow-up \nappointment with your healthcare provider to discuss \nany ongoing symptoms and explore other potential causes.\n - Symptom Management: Continue to monitor your \nsymptoms and use any prescribed or over-the-counter \nmedications as directed to manage your discomfort. - Preventive Measures: Maintain healthy practices such as \nregular hand washing, staying hydrated, and avoiding \nclose contact with individuals who are ill. \nIf you have any questions or concerns, please do not hesitate to contact us, we are here to support you and provide any additional information or care you may need. \nThank you for trusting us with your health. ";
  static const highSuspesion =
      "( You have High Suspicion of Pneumonia) \nBased on the information you provided, there is a high suspicion that you may have pneumonia, your responses indicate symptoms and risk factors commonly associated with this condition. \nPneumonia is a serious respiratory infection that requires medical attention; Common symptoms include cough, fever, shortness of breath, chest pain, fatigue, and chills; Your survey responses suggest that you may be experiencing one or more of these symptoms. \nPlease contact your healthcare provider to schedule an appointment for a thorough examination and appropriate testing. Early diagnosis and treatment are crucial for managing pneumonia effectively. \nIf you experience severe symptoms such as difficulty breathing, persistent chest pain, confusion, or high fever, please seek immediate medical attention. \nWe recommend the following steps:\n - Seek Medical Attention Immediately: We strongly recommend that you contact your healthcare provider or visit an urgent care center or emergency room as soon as possible. Pneumonia can be a serious condition that requires prompt medical evaluation and treatment. \n- Describe Your Symptoms: When you speak with your healthcare provider, be sure to describe all the symptoms you are experiencing, including any fever, cough, shortness of breath, chest pain, or fatigue.\n - Share Your Survey Results: Inform your healthcare provider that you completed a survey which indicated a high suspicion of pneumonia. This can help guide their evaluation and decision\n-making process. Your health and well\n-being are our top priority, please do not delay in seeking medical care. If you have any questions or need further assistance, feel free to contact us.\n Thank you for trusting us with your health, Wishing you a speedy recovery.";
  static const youHave =
      "( You have Pneumonia “Recurrent Pneumonia”) \nFollowing your recent diagnostic evaluation, we have determined that you are experiencing recurrent pneumonia. This conclusion is based on your symptoms, medical history, and the results of the diagnostic tests performed. \nWhat This Means: \nRecurrent pneumonia indicates that you have had multiple episodes of pneumonia within a relatively short period. This condition may be due to various underlying factors, including chronic respiratory conditions, immune system issues, or other health concerns that need further investigation. \nNext Steps: \nTo better understand the cause and extent of your condition, we recommend the following:\n - Chest X-ray:\n  This imaging test will help us visualize your lungs and chest area to identify any abnormalities, infections, or other issues that might be contributing to your recurrent pneumonia.\n - Follow-Up Appointment: \nAfter your chest X-ray, please schedule a follow-up appointment so we can review the results together and discuss the best treatment plan for you. \nRecommendations: \nIn the meantime, we recommend the following measures to help manage your condition and reduce the risk of further episodes:\n - Rest and Hydration: Ensure you get plenty of rest and stay hydrated.\n - Medication: Continue taking any prescribed medications as directed.\n - Avoid Smoking: If you smoke, consider quitting, as smoking can worsen respiratory conditions.\n - Healthy Lifestyle: Maintain a healthy lifestyle with a balanced diet and regular exercise, as advised by your healthcare provider. \nIf you have any questions or need assistance with scheduling your chest X-ray or follow-up appointment, please go to the doctor as soon as possible and feel safe to contact us. \nThank you for your attention to this important matter, we are here to support you through your treatment and recovery, Wishing you a speedy recovery. ";
  static const havefirist =
      "( You have Pneumonia for the first time)\n We have reviewed the results of your recent diagnostic survey, based on the findings, we have determined that you have pneumonia. \nPneumonia is an infection that inflames the air sacs in one or both lungs, which can fill with fluid or pus, causing symptoms such as cough, fever, chills, and difficulty breathing. It is essential to start treatment promptly to manage your symptoms and promote recovery. \nHere are the next steps we recommend:\n - Treatment Plan: We will discuss the appropriate treatment options for you, which may include antibiotics, antiviral medications, rest, and fluids. Depending on the severity of your condition, additional treatments such as oxygen therapy might be necessary.\n - Follow-Up Appointments: Regular follow-up appointments will be scheduled to monitor your progress and make any necessary adjustments to your treatment plan.\n - Self-Care and Monitoring: It's important to rest, stay hydrated, and follow the prescribed treatment regimen. Monitor your symptoms and notify us immediately if you experience worsening symptoms or new issues.\n - Preventive Measures: To prevent future respiratory infections, consider getting vaccinated, practicing good hand hygiene, and avoiding close contact with sick individuals. \nIn the meantime, here are a few recommendations to help you manage your symptoms:\n - Rest.\n - Hydration.\n - Over-the-Counter Medications.\n - Humidifier.\n - Avoid Irritants. \nWe understand that receiving a diagnosis of pneumonia can be concerning, but with proper care and treatment, most people recover fully. \nIn the end, please go to a specialist doctor as soon as possible. \nIf you have any questions or need further assistance, please do not hesitate to contact us. \nThank you for trusting us with your health. ";
  static List<String> message = [];
}
