// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqB0Tap6-9hAjNtdViGQu7YzZh_H4kE6A',
    appId: '1:372718262854:web:4999a675a1773237278847',
    messagingSenderId: '372718262854',
    projectId: 'kook-1dd2c',
    authDomain: 'kook-1dd2c.firebaseapp.com',
    storageBucket: 'kook-1dd2c.appspot.com',
    measurementId: 'G-FFVG6C4MYJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvhCw8xyc2mJqotqePm2nzDaR9m_qBy9I',
    appId: '1:372718262854:android:35170ee0bc46f97e278847',
    messagingSenderId: '372718262854',
    projectId: 'kook-1dd2c',
    storageBucket: 'kook-1dd2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm87XaaPEsDIMBiFey8sfvMYvkAH6h-9E',
    appId: '1:372718262854:ios:ba285296dfc787ad278847',
    messagingSenderId: '372718262854',
    projectId: 'kook-1dd2c',
    storageBucket: 'kook-1dd2c.appspot.com',
    iosBundleId: 'com.example.kook',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm87XaaPEsDIMBiFey8sfvMYvkAH6h-9E',
    appId: '1:372718262854:ios:ba285296dfc787ad278847',
    messagingSenderId: '372718262854',
    projectId: 'kook-1dd2c',
    storageBucket: 'kook-1dd2c.appspot.com',
    iosBundleId: 'com.example.kook',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqB0Tap6-9hAjNtdViGQu7YzZh_H4kE6A',
    appId: '1:372718262854:web:7001173b38666c95278847',
    messagingSenderId: '372718262854',
    projectId: 'kook-1dd2c',
    authDomain: 'kook-1dd2c.firebaseapp.com',
    storageBucket: 'kook-1dd2c.appspot.com',
    measurementId: 'G-Y3PRE07ZVV',
  );
}
